
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const ids=['calendar','debts','dashboard','spending','budget'];let current=2;
function activateTab(i){current=Math.max(0,Math.min(ids.length-1,i));const track=$('#track');track.style.transition='transform .32s cubic-bezier(.22,.85,.32,1)';track.style.transform=`translate3d(${-100*current}vw,0,0)`;$$('.t').forEach((b,idx)=>b.classList.toggle('active',idx===current));}
function initTabs(){document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('.t');if(!b)return;const i=ids.indexOf(b.dataset.tab);if(i>=0)activateTab(i);});document.querySelector('.homeFab').addEventListener('click',()=>activateTab(2));}
function moveGlass(){/* full-bleed glass stays put; no per-tab sizing needed for v2.5 */}
(function(){const viewport=$('#viewport');const track=$('#track');let sx=0,sy=0,dx=0,dragging=false;const thresh=window.innerWidth*0.30;const restr=80;function start(e){const t=e.touches?e.touches[0]:e;sx=t.pageX;sy=t.pageY;dx=0;dragging=true;track.style.transition='none';}function move(e){if(!dragging)return;const t=e.touches?e.touches[0]:e;const dy=Math.abs(t.pageY-sy);if(dy>restr){dragging=false;return;}dx=t.pageX-sx;const base=-100*current;const pct=(dx/window.innerWidth)*100;track.style.transform=`translate3d(calc(${base}vw + ${pct}vw),0,0)`;}function end(){if(!dragging)return;dragging=false;if(Math.abs(dx)>thresh){current+=dx<0?1:-1;current=Math.max(0,Math.min(ids.length-1,current));}track.style.transition='transform .36s cubic-bezier(.22,.85,.32,1)';track.style.transform=`translate3d(${-100*current}vw,0,0)`;dx=0;$$('.t').forEach((b,idx)=>b.classList.toggle('active',idx===current));}viewport.addEventListener('touchstart',start,{passive:true});viewport.addEventListener('touchmove',move,{passive:true});viewport.addEventListener('touchend',end,{passive:true});let md=false;viewport.addEventListener('mousedown',e=>{md=true;start(e)});window.addEventListener('mousemove',e=>{if(md)move(e)});window.addEventListener('mouseup',()=>{if(md){md=false;end()}});})();
window.addEventListener('resize',moveGlass);document.addEventListener('DOMContentLoaded',()=>{activateTab(current);});
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));}
